Algoritmo "loops infinitos"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/09/2023
Var
// Seção de Declarações das variáveis 
i: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 para i de 1 ate 53465644 faça
 escreval ("valor de i: ", i)
 fimpara
Fimalgoritmo